### ISSUE TITLE
Is there a neoforge version?

### ISSUE THREAD

**Issue by yzqdev** [Thomilist/show-durability#6]
It's an awesome plugin, my friends and have been using it for months.Since neoforge is becoming more and more popular, is there a neoforge version?

**Comment by Thomilist** [comment]
Thank you for the kind words :)

To answer the question directly: No, there is not a NeoForge version.

That being said, I'm not opposed to the idea, and this mod is fairly small, so it shouldn't be *too* difficult. Realistically, though, I can't promise this any time soon or even at all. Life has been pretty busy, so I unfortunately don't have as much spare time as I used to.

**Comment by yzqdev** [comment]
Got it, thank you.
